### ISSUE TITLE
OIDCRedisCachePassword - If encrypted with openssl (-apr1) doesnt work

### ISSUE THREAD

**Issue by MukundKMallar** [zmartzone/mod_auth_openidc#359]
Hi 

We are configuring REDIS as the external cache management with mod_auth. Issue we are running into is, when defining OIDCRedisCachePassword in clear text, the connection works. But if i hash the password using (openssl passwd -apr1 myPassword) , it unable to use it for the connection and complains it to be "invalid password".

Actual 
OIDCRedisCachePassword myPassword

New
OIDCRedisCachePassword $apr1$sfd23afda4454345346tYT0

why does module fail to connect if we are using this password? is it a module limitation?

**Comment by zandbelt** [comment]
This type of questions is better suited for the mailing list. 

AFAIK Redis does not support hashed passwords. Do you have reason to believe otherwise?
I also don't see what this feature would add in terms of security. Can you explain?

**Comment by MukundKMallar** [comment]
It threw an error in log, hence the reason to file as an issue. 
Security wise - it is more related to having passwords or passphrases in clear text in the configuration files on Apache. They are scrutinized by internal security team and there is an ask to encrypt this in the configuration file. I understand the use case of encryption for passwords or passphrases are currently not supported in the module , challenge being maintaining the keys so that Apache can encrypt and decrypt the user defined password. Tightening the security just by permission control on Apache and its configuration file is found out to be hardly convincing and taken as an additional measure to primary focus being encrypting the clear text passwords/passphrases. Can we start pursuing an enhancement of these password/passphrases in the module?

**Comment by zandbelt** [comment]
The error is produced by Redis and logged by mod_auth_openidc which is the correct behavior.

I believe you're conflating hashing and encrypting as well as storing passwords server side vs client side. Encryption of passwords client side (vs. hashing which `openssl passwd -apr1 myPassword` does/is) is useful but only if the mechanism for retrieving the encryption key isn't just pushing the problem one level up.

If you can describe how the Apache process would obtain the encryption key and how/why that is better than a non-encrypted password in the config file, we can turn this into an enhancement issue. Otherwise you can propose developments if commercially funded.
