### ISSUE TITLE
Ability to explicitly set the baseURL

### ISSUE THREAD

**Issue by jornane** [zmartzone/mod_auth_openidc#373]
This issue has the same symptom as #282, but the proposed solution won't work in this case. We run a TCP proxy in front of Apache, which means that any X-Forwared-* headers are not set. I have tried forgeing the headers using `RequestHeader append X-Forwarded-Port "443"` but this did not work, I guess the headers are added after mod_auth_openidc looks at the request.

I would like a configuration option to explicitly set the baseURL, which then overrides the value returned by [`oidc_get_current_url_base`](https://github.com/zmartzone/mod_auth_openidc/blob/33647c9ee7c984ea3ad18151810cd8381d7e3a34/src/util.c#L468).

###### Environment

- mod_auth_openidc-1.8.8-3.el7.x86_64
- Apache 2.4.6
- Centos 7

###### Expected behaviour

After logging in, the user is redirected to an URL with the port number the user was communicating with.

###### Actual behaviour

After logging in, the user is redirected to an URL with the port number that Apache is listening on

###### Minimized example

On one host, use a reverse proxy, for example sslh.

	# /etc/sslh.cfg
	verbose: false;
	foreground: true;
	inetd: false;
	numeric: false;
	transparent: false;
	timeout: 5;
	user: "sslh";
	listen:
	(
		{ host: "::"; port: "443"; },
		{ host: "0.0.0.0"; port: "443"; }
	);
	protocols:
	(
		{ name: "ssl"; host: "localhost"; port: "8443"; log_level: 0; }
	);

Then make Apache listen on port 8443.

	<VirtualHost [::1]:8443>
		ServerName	https://example.com:443

		RequestHeader append X-Forwarded-Port "443"
		OIDCProviderMetadataURL https://example.com/.well-known/openid-configuration
		OIDCClientID 00000000-0000-0000-0000-000000000000
		OIDCClientSecret 00000000-0000-0000-0000-000000000000
		OIDCRedirectURI https://example.com/redirect_uri/
		OIDCCryptoPassphrase s3cr3t

		AuthType openid-connect
		Require valid-user
	</VirtualHost>

Navigate to https://example.com and attempt a log in. After logging in, you are redirected back to https://example.com:8443, which will not work.

**Comment by suijlenm** [comment]
Actually I ran into the same "challenge" today. After turning on the highest logging level in Apache and later Googleing for more information I found out that Authentication comes second (just after the core features of apache). This means that the header info is not set in time (like you already found out yourself). To solve this issue you will need to make sure that the port is set directly after the core commands of apache are run. The answer to your problem is actually very simple if you know all this. 

Change "RequestHeader append X-Forwarded-Port 443" to RequestHeader append X-Forwarded-Port 443 early" or "RequestHeader set X-Forwarded-Port 443". That will solve your problem!

**Comment by zandbelt** [comment]
Thanks for the (pretty obvious, afterwards) solution to this problem :-)
I'll leave the ticket open to think about whether it makes sense to include something in mod_auth_openidc rather than relying on a workaround through an external module.

**Comment by zandbelt** [comment]
I actually think this edge case case makes the workaround appropriate enough.
