### ISSUE TITLE
Session is not extended after access_token refreshing

### ISSUE THREAD

**Issue by d-maks** [zmartzone/mod_auth_openidc#381]
I need to propose user extend session (has duration equal id_token lifetime) in some time before it expire. For that I refresh token as explain here [https://github.com/zmartzone/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens](https://github.com/zmartzone/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens). But after access token refreshing id_token remains same and session is not extended.

###### Environment

- mod_auth_openidc version (2.3.7)
- Apache version (2.4.6)
- platform/distro (Linux  3.10.0)

###### Expected behaviour

Token refreshing updates value of all tokens and leads to extension of session duration.

###### Actual behaviour

Token refreshing updates value of access and refresh token, but remains value of id token same and doesn't extend session duration.

###### Configuration and Log files

OIDCClaimPrefix "OIDC-"
OIDCResponseType "code"
OIDCScope "openid"
OIDCProviderIssuer https://my-provider.com
OIDCProviderAuthorizationEndpoint https://my-provider.com/endpoint/authorize
OIDCProviderTokenEndpoint   https://my-provider.com/endpoint/token
OIDCProviderTokenEndpointAuth client_secret_basic
OIDCProviderJwksUri https://example.com/jwks
OIDCClientID clientId
OIDCClientSecret clientSecret
OIDCRedirectURI https://example.com/redirect

OIDCCryptoPassphrase cryptoPassphrase

OIDCSessionInactivityTimeout 3600
OIDCSessionMaxDuration 0
OIDCInfoHook id_token access_token iat access_token_expires userinfo refresh_token session
OIDCUserInfoRefreshInterval 10

**Comment by zandbelt** [comment]
The `id_token` is a token to transfer user identity. The `exp` claim represents the lifetime of the token, which must not be consumed when presented after that timestamp. It is not a token nor claim that sets the lifetime of the resulting application session, that is rather independent and gets refreshed with user activity.

**Comment by BrentVLaere** [comment]
We are also experiencing this behavior. We use the id_token to identify the user in services behind the reverse proxy. What is the reason that the updated id_token is not stored like the updated access_token and refresh_token? https://github.com/zmartzone/mod_auth_openidc/blob/f5959d767b0eec4856d561cbaa6d2262a52da551/src/mod_auth_openidc.c#L1238-L1259

**Comment by fagia** [comment]
@zandbelt I've also recently came across the same lines of code that @BrentVLaere is mentioning.
Which is the reason behind updating the session with the updated access_token but not doing the same with the updated id_token?
We're forwarding both access_token and id_token to a service behind our reverse proxy but, after the exp date of the initial id_token, that service is returning unauthorized error it because we're still forwarding the initial id_token and not the refreshed one.
Isn't it possible to update the session with the updated id_token too?

**Comment by zandbelt** [comment]
in principe the `id_token` represents an authentication event; since the user is not even present in the refresh grant flow, returning a new `id_token` changes the semantics of that; however, by now there are a lot of places where this initial rule is not met and I'm open to a PR that stores the new `id_token`

**Comment by fagia** [comment]
@zandbelt thanks for your answer.
Even though some OpenID Connect providers **can** return new id_token on refresh too (eg: https://auth0.com/docs/tokens/refresh-tokens/use-refresh-tokens), what you're describing it's correct: id_token should be validated only on authentication event and hence it doesn't need to be refreshed...
We'll try to adapt our use cases to just need refreshed access_token and not id_token.
In case you think it could be useful, I can anyway submit the PR to update the id_token in session **if** it's returned as part of a refresh response.
Cheers

**Comment by zandbelt** [comment]
I personally don't think it is useful: the userinfo endpoint should be used to do what people try to achieve with refreshing the id_token; however because of the current state of things I'm willing to merge a PR that makes this behaviour configurable
