### ISSUE TITLE
Configure token endpoint parameters

### ISSUE THREAD

**Issue by ecattez** [zmartzone/mod_auth_openidc#402]
###### Environment

- mod_auth_openidc version: 2.3.8
- Apache version: 2.4.6
- platform/distro: RedHat 7

###### Expected behaviour

We should explicitly set the parameter names sent to the token endpoint instead of sending them all.

###### Actual behaviour

Hi, in our company, we used FranceConnect. This is a governmental open-id provider. Actually, we're using a SpringBoot based application to orchestrate our calls between a Portal and the FC Provider. But, there is an Apache in front of our Portal. So we think that the mod_auth_openidc should be a better way to interact with OpenID Connect.

FranceConnect Token Endpoint only accepts the body below : 

```
'grant_type': 'authorization_code',
'redirect_uri': '<FS_URL>/<URL_CALLBACK>',
'client_id': '<CLIENT_ID>',
'client_secret': '<CLIENT_SECRET>',
'code': '<AUTHZ_CODE>'
```

The problem is that the mod_auth_openidc sends the `state` attribute, resulting in the following error from FC : 

 `response={"status":"fail","message":"The following fields are not supposed to be present : state"}`

We don't believe that the governement would accept our request to allow the `state` attribute.... So here we are.

Regards,

**Comment by zandbelt** [comment]
The addition of the `state` parameter in the call to the token endpoint was done to mitigate certain attacks, see: https://tools.ietf.org/html/draft-ietf-oauth-security-topics-08#section-3.5.1.

Whilst one could argue that your OP is broken since it should ignore unknown parameters (https://tools.ietf.org/html/rfc6749#section-3.2), I will grant you that making it a configurable option could be seen as an interoperability improvement.

**Comment by ecattez** [comment]
@zandbelt Thank you for your work !
