### ISSUE TITLE
Cached pages donot go through authentication

### ISSUE THREAD

**Issue by sunayanasarangi** [zmartzone/mod_auth_openidc#408]
Hi all,

i am facing a problem with authenticating pages that are cached by the browser. The application that I am protecting using mod_auth_openidc module needs browser caching since the pages have a lot of content and the reload gets very slow if caching is deactivated. But this causes authentication problems. After a logout, if I access any cached page, I can access it without having to go through any authentication. How can I enforce that cached/non cached pages all go through authentication? 

mod_auth_openidc version = 2.3.8
Apache version = 2.4.18
Ubuntu 16.04

I would greatly appreciate any help.

Thanks,
Sunayana

**Comment by zandbelt** [comment]
you cannot: your requirements contradict each other

**Comment by dwaite** [comment]
You might be able to do this with RFC 7232 (Conditional Requests) and RFC 7234 (Caching). Most authenticated and generated content these days disable caching completely as to not risk leakage of information. In these environments, cached content is pushed as much as possible to unauthenticated, static locations (such as a separate resource server in HTTP/1.1 environments)

I'm not really giving advice, rather fuel for experimentation to see if you can use these to craft a policy that works for your environment. My last foray into HTTP caching was nearly 20 years ago, a more complex and broken time, long before either of those revised/improved RFCs.

In particular, I would imagine that setting a cache policy would mean you want to verify behavior across browsers, over TLS as mandated by OAuth/OIDC, and through any proxies like nginx/varnish (which are much more about administrative policy than conformance to the HTTP RFCs.)

You should also understand that your caching policy is really more about conditional display to the user and UX; the content was sent and thus software in the path of the request/response of that content may have held onto it. If you have concerns about cached content remaining on disk after logout, I honestly don't know if the browsers provide behavior or a mechanism (either `Cache-Control` or other) to clear that content.

Disclaimers stated, I'd point you toward some combination of headers on responses:

- `Vary: Cookie` (and on `Authorization`) to indicate that a cache needs to key on the Cookie/Authorization values of the request rather than simply return a response
- `Last-Modified` or `ETag` to indicate the browser should make conditional requests for content. It sounds like you don't care about hitting the server with requests, but rather having the browser wait on big responses.
- `Cache-Control` of `must-revalidate` / `no-cache` to indicate that the server must make another request if the response is stale, and must fail if the server is unavailable
- `Cache-Control` should also specific `public` or `private` depending on your policy needs. I believe (at least) Firefox will use public/private to determine whether the content should be persisted to disk cache vs only existing within the in-memory cache.
- Finally, for safety make sure your `no-cache` indicates that values of the `Set-Cookie` header should not be sent on future responses.

Note you *also* may be able to do this for some applications via Service Workers, with programmatic control of caching. I can't speak to whether this gives you access to the same capabilities as the browser-level caching, however.

**Comment by Sunayana-Sarangi** [comment]
Hi David,

thankyou for your reply, I just bumped on your message now, hence this delay. What you have written is a ton of information that I would slowly need to process and understand. I am new to this area but looks like I do make some sense out of things that you have written and I will experiement and see what I get. If I am able to find something interesting, I will comment back on this thread. Thanks again for taking the time to explain and suggest.
