### ISSUE TITLE
OIDCInfoHook doesn't work with version 2.4.5

### ISSUE THREAD

**Issue by adrienyhuel** [zmartzone/mod_auth_openidc#512]
Hello,

I was using version 2.4.4.1 and made calls to /authorize?info=json url in my webapp in order to display access_token to the user.

Since I updated to 2.4.5, this url is not intercepted by mod_auth_openidc and is forward to my webapp (which respond a 404 error).

I did not change my Apache conf : 

OIDCInfoHook iat access_token access_token_expires id_token userinfo refresh_token session

Is this a bug in version 2.4.5, or do I have to change something in my config ?

**Comment by zandbelt** [comment]
I just checked that it still works for me. perhaps the debug logs would tell you more about what happens.

**Comment by Tvirtues** [comment]
Hello, have you solved this problem?I had the same problem when I upgraded to 2.4.5, "Redirect /?Info =json "can not get user name, 2.4.5 version does not have this problem, really confusing

**Comment by Tvirtues** [comment]
Hello, have you solved this problem?I had the same problem when I upgraded to 2.4.5, "Redirect /?Info =json "can't get a user name, version 2.4.5 and below does not have this problem, really confusing

**Comment by EtoHummin** [comment]
I ran into this problem as well and tracked it down to 2 separate issues in my case. I believe it has to do mostly with 9111e56fa83fa05503b4b5e919b72a5641dd0942 which reorders the content handler processing and sends `info` requests down a completely separate path.

Fix 1:
```
<Location /[OIDCRedirectURI Path]>
      AuthType auth-openidc
      Require valid-user
</Location>
```
I do not know why this worked over the `Include claims.conf` on `Location /` but it fixed nearly all of my systems.

When I deployed that change, some systems still returned 401 only on `?info` requests, in their logs I found:

`oidc_check_cookie_domain: aborting: detected attempt to play cookie against a different domain/host than issued for! (issued=mysite.com, current=mysite-abc12345.s3.us-east-1.amazonaws.com)`

This is due to the reordered processing now evaluating `oidc_check_cookie_domain` AFTER a `Host:` header rewrite.

Fix 2:
```
OIDCCookieDomain mysite.com
```
